apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-frontend-html
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.frontend.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
   - port: {{ .Values.frontend.service.port }}
     targetPort: 5000
     protocol: TCP
     name: http
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
