{{- if .Values.backendapi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "backendapi.fullname" . }}-backend-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backendapi.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "backendapi.fullname" . }}-backend-api
  minReplicas: {{ .Values.backendapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backendapi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.backendapi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backendapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.backendapi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.backendapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
