{{- if .Values.backendapi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backendapi.serviceAccountName" . }}-backend-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backendapi.labels" . | nindent 4 }}
  {{- with .Values.backendapi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false 
{{- end }}
